name: starter-spring

services:

  # Spring Boot API Service
  api:
    depends_on:
      starterdb:
        condition: service_healthy
    deploy:
      # Memory limit for the API service
      resources:
        limits:
          memory: 512M
    environment:
      SPRING_CLOUD_CONFIG_URI: ${SPRING_CLOUD_CONFIG_URI}
      SPRING_CLOUD_CONFIG_USERNAME: ${SPRING_CLOUD_CONFIG_USERNAME}
      SPRING_CLOUD_CONFIG_PASSWORD: ${SPRING_CLOUD_CONFIG_PASSWORD}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_APPLICATION_NAME: ${SPRING_APPLICATION_NAME}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://api:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    hostname: api
    image: ghcr.io/tiogars/starter-api-spring-mysql:latest
    #networks:
    #  - starter_api_network
    # ports:
    #   - "8080:8080"
  # MySQL Database Service
  starterdb:
    hostname: starterdb
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "starterdb"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 512M
    #networks:
    #  - starter_api_network
    volumes:
      - mysql-data:/var/lib/mysql

networks:
  #starter_api_network:
   # driver: bridge

volumes:
  mysql-data:
    