name: starter-api-spring-mysql

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: starterdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  app-local:
    image: starter-react-vite
    ports:
      - "8080:80"
  app:
    image: ghcr.io/tiogars/starter-react-vite:v0.0.2
    ports:
      - "8082:80"
  api:
    # https://github.com/tiogars/starter-api-spring-mysql/pkgs/container/starter-api-spring-mysql
    image: ghcr.io/tiogars/starter-api-spring-mysql:latest
    ports:
      - "8081:8080"
  api-local:
    build:
      context: .
      dockerfile: Dockerfile
    # environment:
    #   - 
    ports:
      - "8081:8080"

volumes:
  mysql-data: