name: starter-spring

services:

  # Spring Boot API Service
  api:
    depends_on:
      starterdb:
        condition: service_healthy
    deploy:
      # Memory limit for the API service
      resources:
        limits:
          cpus: "2.0"
          memory: 512M
        reservations:
          cpus: "1.0"
          memory: 256M
    environment:
      SPRING_CLOUD_CONFIG_URI: ${SPRING_CLOUD_CONFIG_URI}
      SPRING_CLOUD_CONFIG_USERNAME: ${SPRING_CLOUD_CONFIG_USERNAME}
      SPRING_CLOUD_CONFIG_PASSWORD: ${SPRING_CLOUD_CONFIG_PASSWORD}
      SPRING_PROFILES_ACTIVE: production
      SPRING_APPLICATION_NAME: starter_api
      SPRINGDOC_SWAGGER_UI_ENABLED: "true"
      SPRINGDOC_API_DOCS_PATH: /api-docs
      SPRINGDOC_SWAGGER_UI_PATH: /swagger-ui.html
      SPRINGDOC_SHOW_ACTUATOR: "true"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://api:9462/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    hostname: api
    image: ghcr.io/tiogars/starter-api-spring-mysql:latest
    labels:
      - flame.type=application
      - flame.name=starter-api-spring-mysql
      - flame.url=https://starter-api.tiogars.fr/swagger-ui/index.html
      - flame.icon=docker
    networks:
      - starter_api_network
    ports:
      - "9462:9462"
    # expose:
    #   - 9462
    pull_policy: always

  # MySQL Database Service
  starterdb:
    hostname: starterdb
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: starterdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    networks:
      - starter_api_network
    volumes:
      - mysql-data:/var/lib/mysql

networks:
  starter_api_network:
    driver: bridge

volumes:
  mysql-data:
    
