debug: false
spring:
  application:
    name: ${SPRING_APPLICATION_NAME:starter_api}
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  cloud:
    config:
      # name: ${SPRING_APPLICATION_NAME:starter_api}
      uri: ${SPRING_CLOUD_CONFIG_URI:http://localhost:8888}
      username: ${SPRING_CLOUD_CONFIG_USERNAME}
      password: ${SPRING_CLOUD_CONFIG_PASSWORD}
  config:
    import: optional:configserver:${SPRING_CLOUD_CONFIG_URI:http://localhost:8888}
