debug: false
spring:
  application:
    name: ${SPRING_APPLICATION_NAME:starter_api}
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  cloud:
    config:
      name: ${SPRING_APPLICATION_NAME:starter_api}
      label: ${SPRING_CLOUD_CONFIG_LABEL:main}
      uri: ${SPRING_CLOUD_CONFIG_URI:http://localhost:8888}
      username: ${SPRING_CLOUD_CONFIG_USERNAME}
      password: ${SPRING_CLOUD_CONFIG_PASSWORD}
  config:
    import: optional:configserver:${SPRING_CLOUD_CONFIG_URI:http://localhost:8888}
  datasource:
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 300000
      max-lifetime: 600000
      connection-test-query: SELECT 1
  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
