# Default application.yml
# spring:
#     application:
#         name: ${SPRING_APPLICATION_NAME}
#     config:
#         name: ${SPRING_APPLICATION_NAME}
#         import: ${SPRING_CONFIG_IMPORT}
#     profiles:
#         active:
#             - ${spring.profiles.active}

# ---

# Development application.yml
spring:
  application:
    name: starter
  datasource:
    url: jdbc:mysql://mysql:3306/starterdb
    username: root
    password: rootpassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  messages:
    basename:
    - messages,config.i18n.messages
# http://localhost:8080/
server:
  port: 8080
# http://localhost:8080/actuator/health
management:
  endpoints:
    web:
      exposure:
        include: health,info
springdoc:
  show-actuator: true