name: Release

on:
  workflow_dispatch:
    inputs:
      nextSnapshotIndexToIncrement:
        description: 'Index of the snapshot version to increment (1-based) ; ex:
          - for 1, 1.0.0-SNAPSHOT -> 2.0.0
          - for 2, 1.0.0-SNAPSHOT -> 1.1.0
          - for 3, 1.0.0-SNAPSHOT -> 1.0.1'
        required: false
        default: '3'

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Setup
      - uses: actions/checkout@v6

      - uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      # Current version
      - name: Get tag version before release
        id: get_tag_version_before_release
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "VERSION_BEFORE_RELEASE=$VERSION" >> $GITHUB_OUTPUT

      - name: Display current version
        run: echo "Current version is ${{ steps.get_tag_version_before_release.outputs.VERSION_BEFORE_RELEASE }}"

      # Release
      - run: mvn versions:set -DremoveSnapshot=true

      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn clean install

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.get_tag_version_before_release.outputs.VERSION }}
            ghcr.io/${{ github.repository }}:latest

      # Next snapshot version
      - run: mvn versions:set -DnextSnapshot=true -DnextSnapshotIndexToIncrement=${{ github.event.inputs.nextSnapshotIndexToIncrement }}

      - name: Get tag version after release
        id: get_tag_version_after_release
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "VERSION_AFTER_RELEASE=$VERSION" >> $GITHUB_OUTPUT

      - name: Display next version
        run: echo "Next version is ${{ steps.get_tag_version_after_release.outputs.VERSION_AFTER_RELEASE }}"

      # Commit version changes
      - name: Commit version changes
        run: mvn versions:commit
